CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY NOT NULL,
  login VARCHAR(15) NOT NULL UNIQUE,
  password VARCHAR(15) NOT NULL,
  name VARCHAR(30) NOT NULL
);
CREATE TABLE IF NOT EXISTS todos (
  id BIGSERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER NOT NULL,
  title VARCHAR(200) NOT NULL,
  completed BOOLEAN NOT NULL DEFAULT FALSE,
  date_create TIMESTAMP NOT NULL DEFAULT NOW()
);