bind_addr = ":8080"
log_level =  "debug"
session_key = "10101010101010100101010101001"

[database]
    host = "127.0.0.1"
    port = "5432" 
    user = "postgres" 
    password = "" 
    database = "name_database" 
    sslmode = "disable"
